changed the include order to avoid bad interactions between oci.h and zlib.
with the previous include order, we run with recent oracle cersions (19.5) into
    /usr/include/zlib.h:1677:4: error: unknown type name ‘off64_t’
on 64bit linux systems (centos 7)

ns.h should be self contained, so the bunch of include files seems not necessary (anymore)